cabal-version: 2.4
name:          hnvr-ptz
version:       0.1.0.0
synopsis:      HNVR PTZ control: ONVIF client + state machine
license:       BSD-3-Clause
build-type:    Simple

library
  exposed-modules:
    Hnvr.Ptz.Controller
    Hnvr.Ptz.Driver
    Hnvr.Ptz.Onvif

  build-depends:
    , base        >=4.18 && <5
    , bytestring
    , hnvr-core
    , hnvr-nats
    , text

  hs-source-dirs:   src
  default-language: Haskell2010
