cabal-version: 2.4
name:          hnvr-cv
version:       0.1.0.0
synopsis:
  HNVR computer vision: ONNX runtime, YOLO decode, SORT tracker, rules

license:       BSD-3-Clause
build-type:    Simple

library
  exposed-modules:
    Hnvr.Cv.Analyzer
    Hnvr.Cv.AnalyzerRunner
    Hnvr.Cv.AutoTrack
    Hnvr.Cv.DebugRender
    Hnvr.Cv.Decode
    Hnvr.Cv.OnnxRuntime
    Hnvr.Cv.OnnxRuntime.Internal
    Hnvr.Cv.Preprocess
    Hnvr.Cv.Rules
    Hnvr.Cv.Tracker.Hungarian
    Hnvr.Cv.Tracker.Kalman
    Hnvr.Cv.Tracker.Sort

  build-depends:
    , aeson
    , base         >=4.18 && <5
    , bytestring
    , containers
    , directory
    , ghc-prim
    , hnvr-core
    , JuicyPixels
    , massiv
    , scientific
    , stm
    , text
    , time
    , unix
    , vector

  hs-source-dirs:   src
  default-language: Haskell2010

executable hnvr-leak-probe
  main-is:          LeakProbe.hs
  hs-source-dirs:   app
  build-depends:
    , base
    , deepseq
    , hnvr-core
    , hnvr-cv
    , random
    , text
    , time
    , vector

  default-language: Haskell2010
  ghc-options:      -threaded -rtsopts -with-rtsopts=-N

executable hnvr-cv-soak
  main-is:          Soak.hs
  hs-source-dirs:   app
  build-depends:
    , async
    , base
    , containers
    , hnvr-capture
    , hnvr-core
    , hnvr-cv
    , stm
    , text
    , time

  default-language: Haskell2010
  ghc-options:      -threaded -rtsopts -with-rtsopts=-N

executable hnvr-cv-compare
  main-is:          CompareModels.hs
  hs-source-dirs:   app
  build-depends:
    , async
    , base
    , bytestring
    , containers
    , directory
    , filepath
    , hnvr-capture
    , hnvr-core
    , hnvr-cv
    , stm
    , text
    , vector

  default-language: Haskell2010
  ghc-options:      -threaded -rtsopts -with-rtsopts=-N

test-suite hnvr-cv-test
  type:             exitcode-stdio-1.0
  main-is:          Main.hs
  hs-source-dirs:   test
  other-modules:
    Hnvr.Cv.AnalyzerRunnerSpec
    Hnvr.Cv.AnalyzerSpec
    Hnvr.Cv.DebugRenderSpec
    Hnvr.Cv.DecodeSpec
    Hnvr.Cv.OnnxRuntimeSpec
    Hnvr.Cv.PreprocessSpec
    Hnvr.Cv.RulesSpec
    Hnvr.Cv.TrackerSpec

  build-depends:
    , async
    , base              >=4.18 && <5
    , bytestring
    , containers
    , deepseq
    , directory
    , filepath
    , hnvr-core
    , hnvr-cv
    , JuicyPixels
    , massiv
    , QuickCheck
    , random
    , stm
    , tasty
    , tasty-hunit
    , tasty-quickcheck
    , text
    , time
    , vector

  default-language: Haskell2010
  ghc-options:      -threaded -rtsopts "-with-rtsopts=-N -A64m -I0"
