{-# LANGUAGE OverloadedStrings #-}

-- | HNVR web/leader shared library.
--
-- This module exposes a tiny stable API ('version') for embedders (the
-- @hnvr-leader@ and @hnvr-node@ binaries). IHP wiring lives in
-- 'Hnvr.Web.Config' and 'Hnvr.Web.FrontController'; pull those in
-- transitively by depending on the @hnvr-web@ package directly.
--
-- Versioning convention: the single source of truth is the
-- @version:@ field in @hnvr-web.cabal@, re-exported here via the
-- autogenerated @Paths_hnvr_web@ module. Bump it on every feature or
-- patch: new feature → second component, patch/fix → third (or later)
-- component. The version is logged at binary startup and served on
-- the @/status@ JSON endpoint.
module Hnvr.Web
  ( version,
    versionText,
  )
where

import Data.Text (Text)
import qualified Data.Text as T
import Data.Version (showVersion)
import qualified Paths_hnvr_web

-- | Package version from hnvr-web.cabal (e.g. "0.2.0.0").
version :: Text
version = T.pack (showVersion Paths_hnvr_web.version)

-- | Human-readable log/UI form, e.g. "hnvr v0.2.0.0".
versionText :: Text
versionText = "hnvr v" <> version
